// Generated by scripts/build.mjs — do not edit; edit src/client instead.
window.__ModuleLoader__.load({
	id: "dsh-git-commit-panel",
	factory: (require) => {
		var module = { exports: {} };
		var exports = module.exports;
		Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/client/index.ts
var index_exports = {};
__export(index_exports, {
  GitCommitApi: () => GitCommitApi,
  Panel: () => Panel,
  ROUTE_PREFIX: () => ROUTE_PREFIX,
  apply: () => apply,
  inject: () => inject
});
module.exports = __toCommonJS(index_exports);

// src/types.ts
function isRecord(value) {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
var ERROR_CODES = [
  "bad-request",
  "workspace-unknown",
  "not-a-repository",
  "git-failed",
  "nothing-to-commit",
  "model-unavailable",
  "model-failed",
  "push-failed",
  "internal"
];
function isGitCommitError(value) {
  if (!isRecord(value)) return false;
  if (typeof value.code !== "string" || !ERROR_CODES.includes(value.code)) return false;
  if (typeof value.message !== "string") return false;
  return value.detail === void 0 || typeof value.detail === "string";
}

// src/client/api.ts
var ROUTE_PREFIX = "git-commit";
var TRANSPORT_ERROR = {
  code: "internal",
  message: "The git commit panel could not reach the host."
};
async function post(route, payload, signal) {
  let response;
  try {
    response = await fetch(`${ROUTE_PREFIX}/${route}`, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify(payload),
      ...signal === void 0 ? {} : { signal }
    });
  } catch {
    return { ok: false, error: TRANSPORT_ERROR };
  }
  try {
    const envelope = await response.json();
    if (typeof envelope !== "object" || envelope === null) return { ok: false, error: TRANSPORT_ERROR };
    const record = envelope;
    if (record.ok === true) return { ok: true, value: record.value };
    return { ok: false, error: isGitCommitError(record.error) ? record.error : TRANSPORT_ERROR };
  } catch {
    return { ok: false, error: TRANSPORT_ERROR };
  }
}
var GitCommitApi = class {
  /** Read one workspace's repository status; `value: null` means "not a repository". */
  status(path, signal) {
    return post("status", { path }, signal);
  }
  /** Read a unified diff, optionally restricted to specific paths. */
  diff(path, options = {}, signal) {
    return post("diff", { path, ...options }, signal);
  }
  /** Ask the host's default model for a Conventional Commit message. */
  generate(path, options = {}, signal) {
    return post("generate", { path, ...options }, signal);
  }
  /** Stage (optionally), commit, and optionally push. */
  commit(input, signal) {
    return post("commit", { ...input }, signal);
  }
};

// src/client/locales.ts
var NS = "gitCommitPanel";
var en = {
  badgeTitle: "Commit changes",
  badgeFiles: "{count} changed",
  title: "Commit changes",
  close: "Close",
  refresh: "Refresh",
  branch: "Branch",
  detached: "detached HEAD",
  upstreamAheadBehind: "\u2191{ahead} \u2193{behind}",
  fileCount: "{total} changed \xB7 {staged} staged \xB7 {unstaged} unstaged",
  messageLabel: "Commit message",
  messagePlaceholder: "feat: describe the change",
  hintLabel: "Context for the AI (optional)",
  hintPlaceholder: "Anything the diff does not show?",
  generate: "Generate with AI",
  generating: "Generating\u2026",
  commit: "Commit",
  commitAndPush: "Commit & Push",
  committing: "Committing\u2026",
  pushing: "Pushing\u2026",
  stageAll: "Stage all changes before committing",
  stageAllHint: "Includes untracked files.",
  commitStagedOnly: "Only already-staged changes will be committed.",
  noUnstaged: "No unstaged changes in this workspace.",
  noStaged: "Nothing is staged yet.",
  repository: "Repository",
  workspace: "Workspace",
  generateFailed: "Could not generate a commit message.",
  commitFailed: "Commit failed.",
  showFiles: "Show changed files",
  hideFiles: "Hide changed files",
  commits: "Commit",
  andPush: "and push",
  emptyGenerates: "Leave the message empty and the AI drafts one, then commits.",
  generatedBy: "Drafted by {model}"
};
var zh = {
  badgeTitle: "\u63D0\u4EA4\u66F4\u6539",
  badgeFiles: "{count} \u4E2A\u66F4\u6539",
  title: "\u63D0\u4EA4\u66F4\u6539",
  close: "\u5173\u95ED",
  refresh: "\u5237\u65B0",
  branch: "\u5206\u652F",
  detached: "\u6E38\u79BB HEAD",
  upstreamAheadBehind: "\u2191{ahead} \u2193{behind}",
  fileCount: "\u5171 {total} \u4E2A\u66F4\u6539 \xB7 \u5DF2\u6682\u5B58 {staged} \xB7 \u672A\u6682\u5B58 {unstaged}",
  messageLabel: "\u63D0\u4EA4\u4FE1\u606F",
  messagePlaceholder: "feat: \u63CF\u8FF0\u672C\u6B21\u6539\u52A8",
  hintLabel: "\u7ED9 AI \u7684\u8865\u5145\u8BF4\u660E\uFF08\u53EF\u9009\uFF09",
  hintPlaceholder: "diff \u91CC\u770B\u4E0D\u51FA\u6765\u7684\u610F\u56FE\uFF1F",
  generate: "AI \u751F\u6210",
  generating: "\u751F\u6210\u4E2D\u2026",
  commit: "\u63D0\u4EA4",
  commitAndPush: "\u63D0\u4EA4\u5E76\u63A8\u9001",
  committing: "\u63D0\u4EA4\u4E2D\u2026",
  pushing: "\u63A8\u9001\u4E2D\u2026",
  stageAll: "\u63D0\u4EA4\u524D\u6682\u5B58\u5168\u90E8\u66F4\u6539",
  stageAllHint: "\u5305\u542B\u672A\u8DDF\u8E2A\u7684\u6587\u4EF6\u3002",
  commitStagedOnly: "\u53EA\u4F1A\u63D0\u4EA4\u5DF2\u6682\u5B58\u7684\u66F4\u6539\u3002",
  noUnstaged: "\u8BE5\u5DE5\u4F5C\u533A\u6CA1\u6709\u672A\u6682\u5B58\u7684\u66F4\u6539\u3002",
  noStaged: "\u5F53\u524D\u6CA1\u6709\u5DF2\u6682\u5B58\u7684\u66F4\u6539\u3002",
  repository: "\u4ED3\u5E93",
  workspace: "\u5DE5\u4F5C\u533A",
  generateFailed: "\u65E0\u6CD5\u751F\u6210\u63D0\u4EA4\u4FE1\u606F\u3002",
  commitFailed: "\u63D0\u4EA4\u5931\u8D25\u3002",
  showFiles: "\u5C55\u5F00\u66F4\u6539\u6587\u4EF6",
  hideFiles: "\u6536\u8D77\u66F4\u6539\u6587\u4EF6",
  commits: "\u63D0\u4EA4",
  andPush: "\u5E76\u63A8\u9001",
  emptyGenerates: "\u7559\u7A7A\u5219\u7531 AI \u8D77\u8349\u63D0\u4EA4\u4FE1\u606F\u5E76\u76F4\u63A5\u63D0\u4EA4\u3002",
  generatedBy: "\u7531 {model} \u8D77\u8349"
};

// src/client/Panel.tsx
var import_react = require("react");
var import_jsx_runtime = require("react/jsx-runtime");
var POLL_INTERVAL_MS = 2e4;
var SCAN_MIN_INTERVAL_MS = 3e3;
var KIND_MARK = {
  added: "A",
  modified: "M",
  deleted: "D",
  renamed: "R",
  copied: "C",
  typechange: "T",
  unmerged: "U",
  untracked: "?"
};
var PANEL_TOP_PX = 120;
var panelRootBase = {
  position: "absolute",
  top: `calc(var(--dsh-frame-top-clearance, 0px) + ${PANEL_TOP_PX}px)`,
  right: 14,
  pointerEvents: "auto"
};
var panelStyle = {
  display: "flex",
  flexDirection: "column",
  gap: 10,
  width: "min(420px, calc(100vw - 40px))",
  padding: 16,
  borderRadius: "var(--dsw-radius-panel)",
  background: "var(--dsw-alias-bg-layer-2)",
  color: "var(--dsw-alias-label-primary)",
  boxShadow: "var(--dsw-elevation-prominent)",
  fontFamily: "var(--dsw-font-family)",
  fontSize: "var(--dsw-font-xs-13-font-size)",
  lineHeight: "var(--dsw-font-xs-13-line-height)"
};
var badgeStyle = {
  display: "inline-flex",
  alignItems: "center",
  gap: 8,
  height: 32,
  padding: "0 14px",
  borderRadius: "var(--dsw-radius-panel)",
  cursor: "pointer",
  background: "var(--dsw-alias-button-floating-fill)",
  color: "var(--dsw-alias-label-primary)",
  border: ".5px solid var(--dsw-alias-border-l2)",
  boxShadow: "var(--dsw-elevation-panel)",
  fontFamily: "var(--dsw-font-family)",
  fontSize: "var(--dsw-font-xs-13-font-size)",
  lineHeight: "var(--dsw-font-xs-13-line-height)"
};
var buttonBase = {
  boxSizing: "border-box",
  height: 28,
  padding: "0 12px",
  borderRadius: "var(--dsw-radius-sm)",
  cursor: "pointer",
  fontFamily: "var(--dsw-font-family)",
  fontSize: "var(--dsw-font-xs-13-font-size)",
  lineHeight: "var(--dsw-font-xs-13-line-height)",
  fontWeight: "var(--dsw-font-xs-13-font-weight)"
};
var terseButton = {
  ...buttonBase,
  background: "transparent",
  color: "var(--dsw-alias-label-primary)",
  border: ".5px solid var(--dsw-alias-border-l4)"
};
var primaryButton = {
  ...buttonBase,
  background: "var(--dsw-alias-button-primary-fill)",
  color: "var(--dsw-alias-label-primary-foreground)",
  border: ".5px solid transparent",
  fontWeight: 500
};
var inputStyle = {
  width: "100%",
  boxSizing: "border-box",
  padding: "6px 10px",
  borderRadius: "var(--dsw-radius-lg)",
  resize: "vertical",
  background: "var(--dsw-alias-bg-layer-1)",
  color: "var(--dsw-alias-label-primary)",
  border: ".5px solid var(--dsw-alias-border-l4)",
  fontFamily: "var(--dsw-font-family)",
  fontSize: "var(--dsw-font-xs-13-font-size)",
  lineHeight: "var(--dsw-font-xs-13-line-height)"
};
var fileRowStyle = {
  display: "flex",
  alignItems: "center",
  gap: 8,
  padding: "2px 0",
  whiteSpace: "nowrap",
  overflow: "hidden"
};
var mutedStyle = {
  color: "var(--dsw-alias-label-caption)",
  fontSize: "var(--dsw-font-xxs-12-font-size)",
  lineHeight: "var(--dsw-font-xxs-12-line-height)"
};
var statStyle = {
  display: "inline-flex",
  gap: 6,
  fontVariantNumeric: "tabular-nums"
};
var additionStyle = { color: "var(--dsw-alias-state-success-primary)" };
var deletionStyle = { color: "var(--dsw-alias-state-error-primary)" };
function HoverButton({
  style,
  hoverStyle,
  ...rest
}) {
  const [hover, setHover] = (0, import_react.useState)(false);
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
    "button",
    {
      type: "button",
      ...rest,
      style: hover && !rest.disabled ? { ...style, ...hoverStyle } : style,
      onMouseEnter: () => setHover(true),
      onMouseLeave: () => setHover(false)
    }
  );
}
var ghostHover = { background: "var(--dsw-alias-interactive-bg-hover)" };
var primaryHover = { background: "var(--dsw-alias-button-primary-hover)" };
function conversationWorkspace(state) {
  for (const row of Object.values(state.byId)) {
    if ((row.retainedBy.mainView ?? 0) > 0) return row.cwd ?? null;
  }
  return null;
}
function Panel(props) {
  const { t, git, useGitCommitStatus, setStatus, useSessions } = props;
  const status = useGitCommitStatus((current) => current ?? null);
  const workspace = useSessions(conversationWorkspace);
  const [open, setOpen] = (0, import_react.useState)(false);
  const [message, setMessage] = (0, import_react.useState)("");
  const [hint, setHint] = (0, import_react.useState)("");
  const [draftedBy, setDraftedBy] = (0, import_react.useState)("");
  const [stageAll, setStageAll] = (0, import_react.useState)(true);
  const [showFiles, setShowFiles] = (0, import_react.useState)(false);
  const [busy, setBusy] = (0, import_react.useState)("idle");
  const [error, setError] = (0, import_react.useState)(null);
  const [notice, setNotice] = (0, import_react.useState)("");
  (0, import_react.useEffect)(() => {
    if (error === null) return;
    console.warn(
      `[dsh-git-commit-panel] ${error.code}: ${error.message}${error.detail === void 0 ? "" : ` \u2014 ${error.detail}`}`
    );
  }, [error]);
  const workspaceRef = (0, import_react.useRef)(workspace);
  workspaceRef.current = workspace;
  const inFlightRef = (0, import_react.useRef)(false);
  const queuedRef = (0, import_react.useRef)(false);
  const lastScanRef = (0, import_react.useRef)(0);
  const mountedRef = (0, import_react.useRef)(true);
  (0, import_react.useEffect)(() => () => {
    mountedRef.current = false;
  }, []);
  const probe = (0, import_react.useCallback)(async (path) => {
    const result = await git.status(path);
    if (!result.ok) return null;
    const value = result.value;
    if (value === null || !value.hasUnstagedChanges) return null;
    return value;
  }, [git]);
  const refresh = (0, import_react.useCallback)(async (force) => {
    if (inFlightRef.current) {
      queuedRef.current = true;
      return;
    }
    const now = Date.now();
    if (!force && now - lastScanRef.current < SCAN_MIN_INTERVAL_MS) return;
    inFlightRef.current = true;
    try {
      const target = workspaceRef.current;
      const found = target === null ? null : await probe(target);
      if (!mountedRef.current) return;
      setStatus(found);
    } finally {
      inFlightRef.current = false;
      lastScanRef.current = Date.now();
      if (queuedRef.current) {
        queuedRef.current = false;
        void refresh(true);
      }
    }
  }, [probe, setStatus]);
  (0, import_react.useEffect)(() => {
    void refresh(true);
  }, [workspace, refresh]);
  (0, import_react.useEffect)(() => {
    const onFocus = () => {
      void refresh(false);
    };
    const onVisible = () => {
      if (document.visibilityState === "visible") void refresh(false);
    };
    window.addEventListener("focus", onFocus);
    document.addEventListener("visibilitychange", onVisible);
    const timer = window.setInterval(() => {
      if (document.visibilityState === "visible") void refresh(false);
    }, POLL_INTERVAL_MS);
    return () => {
      window.removeEventListener("focus", onFocus);
      document.removeEventListener("visibilitychange", onVisible);
      window.clearInterval(timer);
    };
  }, [refresh]);
  const unstagedFiles = (0, import_react.useMemo)(
    () => (status?.files ?? []).filter((file) => file.unstaged),
    [status]
  );
  const stagedCount = status?.summary.staged ?? 0;
  const additions = status?.lines?.additions ?? 0;
  const deletions = status?.lines?.deletions ?? 0;
  const onRefresh = (0, import_react.useCallback)(() => {
    setError(null);
    void refresh(true);
  }, [refresh]);
  const generateMessage = (0, import_react.useCallback)(async () => {
    if (status === null) return null;
    setError(null);
    setNotice("");
    const result = await git.generate(status.workspace, {
      staged: !stageAll && stagedCount > 0,
      locale: typeof navigator === "undefined" ? "en" : navigator.language,
      ...hint.trim() === "" ? {} : { hint: hint.trim() }
    });
    if (!result.ok) {
      setError(result.error);
      return null;
    }
    setMessage(result.value.message);
    setDraftedBy(result.value.model);
    return { message: result.value.message, model: result.value.model };
  }, [git, hint, stageAll, stagedCount, status]);
  const onGenerate = (0, import_react.useCallback)(async () => {
    setBusy("generating");
    try {
      await generateMessage();
    } finally {
      setBusy("idle");
    }
  }, [generateMessage]);
  const onCommit = (0, import_react.useCallback)(async (push) => {
    if (status === null) return;
    setError(null);
    setNotice("");
    let outgoing = message;
    if (message.trim() === "") {
      setBusy("generating");
      const drafted = await generateMessage();
      if (drafted === null) {
        setBusy("idle");
        return;
      }
      outgoing = drafted.message;
    }
    setBusy("committing");
    try {
      const result = await git.commit({
        path: status.workspace,
        message: outgoing,
        stageAll,
        push
      });
      if (!result.ok) {
        setError(result.error);
        return;
      }
      setMessage("");
      setDraftedBy("");
      setNotice(describeCommit(result.value, t));
      setStatus(null);
      await refresh(true);
    } finally {
      setBusy("idle");
    }
  }, [generateMessage, git, message, refresh, setStatus, stageAll, status, t]);
  if (status === null) return null;
  const branchLabel = status.detached || status.branch === null ? t("detached") : status.branch;
  if (!open) {
    return /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { style: panelRootBase, "data-dsh-git-commit-panel-root": "pill", children: /* @__PURE__ */ (0, import_jsx_runtime.jsxs)(
      HoverButton,
      {
        style: badgeStyle,
        hoverStyle: ghostHover,
        title: t("badgeTitle"),
        "data-dsh-git-commit-panel": "pill",
        onClick: () => setOpen(true),
        children: [
          /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { "aria-hidden": "true", children: "\u2442" }),
          /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { children: branchLabel }),
          /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { style: mutedStyle, children: t("badgeFiles", { count: status.summary.unstaged }) }),
          additions > 0 || deletions > 0 ? /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("span", { style: statStyle, "data-dsh-git-commit-panel": "stat", children: [
            additions > 0 ? /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { style: additionStyle, children: `+${additions}` }) : null,
            deletions > 0 ? /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { style: deletionStyle, children: `-${deletions}` }) : null
          ] }) : null
        ]
      }
    ) });
  }
  const committing = busy === "committing";
  const generating = busy === "generating";
  const hasSomethingToCommit = stageAll ? status.files.length > 0 : stagedCount > 0;
  const canCommit = !busy.startsWith("gen") && !committing && hasSomethingToCommit;
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { style: panelRootBase, "data-dsh-git-commit-panel-root": "card", children: /* @__PURE__ */ (0, import_jsx_runtime.jsxs)(
    "section",
    {
      style: panelStyle,
      role: "dialog",
      "aria-label": t("title"),
      "data-dsh-git-commit-panel": "card",
      children: [
        /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("header", { style: { display: "flex", alignItems: "baseline", gap: 8 }, children: [
          /* @__PURE__ */ (0, import_jsx_runtime.jsx)("strong", { style: { flex: 1 }, children: t("title") }),
          /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { style: mutedStyle, children: branchLabel }),
          status.upstream !== null && (status.ahead > 0 || status.behind > 0) ? /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { style: mutedStyle, children: t("upstreamAheadBehind", { ahead: status.ahead, behind: status.behind }) }) : null,
          /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
            HoverButton,
            {
              style: terseButton,
              hoverStyle: ghostHover,
              "data-dsh-git-commit-panel": "refresh",
              onClick: onRefresh,
              title: t("refresh"),
              children: "\u21BB"
            }
          ),
          /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
            HoverButton,
            {
              style: terseButton,
              hoverStyle: ghostHover,
              "data-dsh-git-commit-panel": "close",
              onClick: () => {
                setOpen(false);
                setError(null);
                setNotice("");
              },
              title: t("close"),
              children: "\u2715"
            }
          )
        ] }),
        /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { style: mutedStyle, children: t("fileCount", {
          total: status.summary.total,
          staged: status.summary.staged,
          unstaged: status.summary.unstaged
        }) }),
        /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
          HoverButton,
          {
            style: { ...terseButton, textAlign: "left" },
            hoverStyle: ghostHover,
            onClick: () => setShowFiles((value) => !value),
            children: showFiles ? t("hideFiles") : t("showFiles")
          }
        ),
        showFiles ? /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { style: { maxHeight: 160, overflow: "auto", fontFamily: "var(--dsw-font-markdown-code-font-family)", fontSize: "var(--dsw-font-markdown-code-font-size)" }, children: [
          unstagedFiles.length === 0 ? /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { style: mutedStyle, children: t("noUnstaged") }) : null,
          unstagedFiles.map((file) => /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { style: fileRowStyle, title: file.path, children: [
            /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { style: { width: 12, flex: "none", opacity: 0.8 }, children: KIND_MARK[file.kind] }),
            /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { style: { overflow: "hidden", textOverflow: "ellipsis" }, children: file.from === void 0 ? file.path : `${file.from} \u2192 ${file.path}` })
          ] }, `${file.path}:${file.from ?? ""}`))
        ] }) : null,
        /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("label", { style: { display: "flex", flexDirection: "column", gap: 4 }, children: [
          /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { style: mutedStyle, children: t("messageLabel") }),
          /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
            "textarea",
            {
              rows: 3,
              style: inputStyle,
              value: message,
              placeholder: t("messagePlaceholder"),
              onChange: (event) => setMessage(event.target.value),
              onKeyDown: (event) => {
                if ((event.metaKey || event.ctrlKey) && event.key === "Enter" && canCommit) {
                  event.preventDefault();
                  void onCommit(false);
                }
              }
            }
          ),
          /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { style: mutedStyle, children: message.trim() === "" ? t("emptyGenerates") : draftedBy === "" ? "" : t("generatedBy", { model: draftedBy }) })
        ] }),
        /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("label", { style: { display: "flex", flexDirection: "column", gap: 4 }, children: [
          /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { style: mutedStyle, children: t("hintLabel") }),
          /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
            "input",
            {
              style: inputStyle,
              value: hint,
              placeholder: t("hintPlaceholder"),
              onChange: (event) => setHint(event.target.value)
            }
          )
        ] }),
        /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("label", { style: { display: "flex", alignItems: "center", gap: 8 }, children: [
          /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
            "input",
            {
              type: "checkbox",
              checked: stageAll,
              onChange: (event) => setStageAll(event.target.checked)
            }
          ),
          /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { children: t("stageAll") }),
          /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { style: mutedStyle, children: t("stageAllHint") })
        ] }),
        !stageAll && stagedCount === 0 ? /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { style: mutedStyle, children: t("noStaged") }) : null,
        error !== null ? /* @__PURE__ */ (0, import_jsx_runtime.jsxs)(
          "div",
          {
            style: { color: "var(--dsw-alias-state-error-primary)", whiteSpace: "pre-wrap" },
            "data-dsh-git-commit-panel": "error",
            children: [
              /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { children: `${t(errorHeading(error.code))} [${error.code}] ${error.message}` }),
              error.detail !== void 0 && error.detail !== "" ? /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { style: { ...mutedStyle, maxHeight: 80, overflow: "auto" }, children: error.detail }) : null
            ]
          }
        ) : null,
        notice !== "" ? /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { style: mutedStyle, children: notice }) : null,
        /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("footer", { style: { display: "flex", gap: 8, justifyContent: "flex-end", flexWrap: "wrap" }, children: [
          /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
            HoverButton,
            {
              style: terseButton,
              hoverStyle: ghostHover,
              disabled: generating || committing,
              onClick: () => {
                void onGenerate();
              },
              children: generating ? t("generating") : t("generate")
            }
          ),
          /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
            HoverButton,
            {
              style: terseButton,
              hoverStyle: ghostHover,
              "data-dsh-git-commit-panel": "commit",
              disabled: !canCommit || committing,
              onClick: () => {
                void onCommit(false);
              },
              children: committing ? t("committing") : t("commit")
            }
          ),
          /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
            HoverButton,
            {
              style: primaryButton,
              hoverStyle: primaryHover,
              "data-dsh-git-commit-panel": "commit-push",
              disabled: !canCommit || committing,
              onClick: () => {
                void onCommit(true);
              },
              children: t("commitAndPush")
            }
          )
        ] })
      ]
    }
  ) });
}
function errorHeading(code) {
  switch (code) {
    case "model-failed":
    case "model-unavailable":
      return "generateFailed";
    default:
      return "commitFailed";
  }
}
function describeCommit(result, t) {
  const head = `${result.commit.slice(0, 8)} ${result.subject}`;
  if (!result.pushed) return head;
  return `${head} \xB7 ${t("commits")} ${t("andPush")}`;
}

// src/client/index.ts
var SLOT = "shell.overlay";
var STATUS_SOURCE = "gitCommitStatus";
var inject = ["slots", "locale", "sessions"];
function apply(ctx) {
  ctx.effect(() => ctx.locale.register(NS, { en, zh }), "dsh-git-commit-panel: dictionaries");
  const git = new GitCommitApi();
  let snapshot = null;
  const listeners = /* @__PURE__ */ new Set();
  const source = {
    getSnapshot: () => snapshot,
    subscribe: (listener) => {
      listeners.add(listener);
      return () => {
        listeners.delete(listener);
      };
    }
  };
  const publish = (next) => {
    if (next === snapshot) return;
    snapshot = next;
    for (const listener of [...listeners]) listener();
  };
  ctx.slots.inject(SLOT, () => ctx.slots.provideRoot({
    hooks: { [STATUS_SOURCE]: source }
  }));
  const Component = (props) => Panel({ ...props, git, setStatus: publish });
  ctx.slots.inject(SLOT, () => {
    const entry = {
      name: SLOT,
      id: "git-commit-panel",
      order: 50,
      locale: NS
    };
    const component = Component;
    return ctx.slots.register(entry, component);
  });
}
		return module.exports;
	}
});
