// Generated by scripts/build.mjs — do not edit; edit src/client instead.
window.__ModuleLoader__.load({
	id: "dsh-git-commit-panel",
	factory: (require) => {
		var module = { exports: {} };
		var exports = module.exports;
		Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/client/index.ts
var index_exports = {};
__export(index_exports, {
  GitCommitApi: () => GitCommitApi,
  Panel: () => Panel,
  ROUTE_PREFIX: () => ROUTE_PREFIX,
  apply: () => apply,
  inject: () => inject
});
module.exports = __toCommonJS(index_exports);

// src/client/api.ts
var ROUTE_PREFIX = "git-commit";
var TRANSPORT_ERROR = {
  code: "internal",
  message: "The git commit panel could not reach the host."
};
async function post(route, payload, signal) {
  let response;
  try {
    response = await fetch(`${ROUTE_PREFIX}/${route}`, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify(payload),
      ...signal === void 0 ? {} : { signal }
    });
  } catch {
    return { ok: false, error: TRANSPORT_ERROR };
  }
  try {
    const envelope = await response.json();
    if (typeof envelope !== "object" || envelope === null) return { ok: false, error: TRANSPORT_ERROR };
    const record = envelope;
    if (record.ok === true) return { ok: true, value: record.value };
    return { ok: false, error: record.error ?? TRANSPORT_ERROR };
  } catch {
    return { ok: false, error: TRANSPORT_ERROR };
  }
}
var GitCommitApi = class {
  /** Read one workspace's repository status; `value: null` means "not a repository". */
  status(path, signal) {
    return post("status", { path }, signal);
  }
  /** Read a unified diff, optionally restricted to specific paths. */
  diff(path, options = {}, signal) {
    return post("diff", { path, ...options }, signal);
  }
  /** Ask the host's default model for a Conventional Commit message. */
  generate(path, options = {}, signal) {
    return post("generate", { path, ...options }, signal);
  }
  /** Stage (optionally), commit, and optionally push. */
  commit(input, signal) {
    return post("commit", { ...input }, signal);
  }
};

// src/client/locales.ts
var NS = "gitCommitPanel";
var en = {
  badgeTitle: "Commit changes",
  badgeFiles: "{count} changed",
  title: "Commit changes",
  close: "Close",
  refresh: "Refresh",
  branch: "Branch",
  detached: "detached HEAD",
  upstreamAheadBehind: "\u2191{ahead} \u2193{behind}",
  fileCount: "{total} changed \xB7 {staged} staged \xB7 {unstaged} unstaged",
  messageLabel: "Commit message",
  messagePlaceholder: "feat: describe the change",
  hintLabel: "Context for the AI (optional)",
  hintPlaceholder: "Anything the diff does not show?",
  generate: "Generate with AI",
  generating: "Generating\u2026",
  commit: "Commit",
  commitAndPush: "Commit & Push",
  committing: "Committing\u2026",
  pushing: "Pushing\u2026",
  stageAll: "Stage all changes before committing",
  stageAllHint: "Includes untracked files.",
  commitStagedOnly: "Only already-staged changes will be committed.",
  noUnstaged: "No unstaged changes in this workspace.",
  noStaged: "Nothing is staged yet.",
  repository: "Repository",
  workspace: "Workspace",
  emptyMessage: "Write a commit message, or let the AI draft one.",
  generateFailed: "Could not generate a commit message.",
  commitFailed: "Commit failed.",
  showFiles: "Show changed files",
  hideFiles: "Hide changed files",
  commits: "Commit",
  andPush: "and push"
};
var zh = {
  badgeTitle: "\u63D0\u4EA4\u66F4\u6539",
  badgeFiles: "{count} \u4E2A\u66F4\u6539",
  title: "\u63D0\u4EA4\u66F4\u6539",
  close: "\u5173\u95ED",
  refresh: "\u5237\u65B0",
  branch: "\u5206\u652F",
  detached: "\u6E38\u79BB HEAD",
  upstreamAheadBehind: "\u2191{ahead} \u2193{behind}",
  fileCount: "\u5171 {total} \u4E2A\u66F4\u6539 \xB7 \u5DF2\u6682\u5B58 {staged} \xB7 \u672A\u6682\u5B58 {unstaged}",
  messageLabel: "\u63D0\u4EA4\u4FE1\u606F",
  messagePlaceholder: "feat: \u63CF\u8FF0\u672C\u6B21\u6539\u52A8",
  hintLabel: "\u7ED9 AI \u7684\u8865\u5145\u8BF4\u660E\uFF08\u53EF\u9009\uFF09",
  hintPlaceholder: "diff \u91CC\u770B\u4E0D\u51FA\u6765\u7684\u610F\u56FE\uFF1F",
  generate: "AI \u751F\u6210",
  generating: "\u751F\u6210\u4E2D\u2026",
  commit: "\u63D0\u4EA4",
  commitAndPush: "\u63D0\u4EA4\u5E76\u63A8\u9001",
  committing: "\u63D0\u4EA4\u4E2D\u2026",
  pushing: "\u63A8\u9001\u4E2D\u2026",
  stageAll: "\u63D0\u4EA4\u524D\u6682\u5B58\u5168\u90E8\u66F4\u6539",
  stageAllHint: "\u5305\u542B\u672A\u8DDF\u8E2A\u7684\u6587\u4EF6\u3002",
  commitStagedOnly: "\u53EA\u4F1A\u63D0\u4EA4\u5DF2\u6682\u5B58\u7684\u66F4\u6539\u3002",
  noUnstaged: "\u8BE5\u5DE5\u4F5C\u533A\u6CA1\u6709\u672A\u6682\u5B58\u7684\u66F4\u6539\u3002",
  noStaged: "\u5F53\u524D\u6CA1\u6709\u5DF2\u6682\u5B58\u7684\u66F4\u6539\u3002",
  repository: "\u4ED3\u5E93",
  workspace: "\u5DE5\u4F5C\u533A",
  emptyMessage: "\u5199\u4E00\u6761\u63D0\u4EA4\u4FE1\u606F\uFF0C\u6216\u8BA9 AI \u8D77\u8349\u4E00\u6761\u3002",
  generateFailed: "\u65E0\u6CD5\u751F\u6210\u63D0\u4EA4\u4FE1\u606F\u3002",
  commitFailed: "\u63D0\u4EA4\u5931\u8D25\u3002",
  showFiles: "\u5C55\u5F00\u66F4\u6539\u6587\u4EF6",
  hideFiles: "\u6536\u8D77\u66F4\u6539\u6587\u4EF6",
  commits: "\u63D0\u4EA4",
  andPush: "\u5E76\u63A8\u9001"
};

// src/client/Panel.tsx
var import_react = require("react");
var import_jsx_runtime = require("react/jsx-runtime");
var POLL_INTERVAL_MS = 2e4;
var SCAN_MIN_INTERVAL_MS = 3e3;
var KIND_MARK = {
  added: "A",
  modified: "M",
  deleted: "D",
  renamed: "R",
  copied: "C",
  typechange: "T",
  unmerged: "U",
  untracked: "?"
};
var panelStyle = {
  position: "absolute",
  right: 20,
  bottom: 20,
  width: "min(420px, calc(100vw - 40px))",
  display: "flex",
  flexDirection: "column",
  gap: 10,
  padding: 14,
  borderRadius: 14,
  pointerEvents: "auto",
  background: "var(--dsw-alias-bg-elevated, var(--dsw-alias-bg-base, Canvas))",
  color: "var(--dsw-alias-label-primary, CanvasText)",
  border: "1px solid var(--dsw-alias-border-secondary, rgba(127,127,127,0.35))",
  boxShadow: "0 12px 32px rgba(0,0,0,0.28)",
  font: '13px/1.5 system-ui, -apple-system, "Segoe UI", sans-serif'
};
var badgeStyle = {
  position: "absolute",
  right: 20,
  bottom: 20,
  display: "inline-flex",
  alignItems: "center",
  gap: 8,
  padding: "8px 14px",
  borderRadius: 999,
  pointerEvents: "auto",
  cursor: "pointer",
  background: "var(--dsw-alias-bg-elevated, var(--dsw-alias-bg-base, Canvas))",
  color: "var(--dsw-alias-label-primary, CanvasText)",
  border: "1px solid var(--dsw-alias-border-secondary, rgba(127,127,127,0.35))",
  boxShadow: "0 8px 24px rgba(0,0,0,0.24)",
  font: '13px/1.4 system-ui, -apple-system, "Segoe UI", sans-serif'
};
var terseButton = {
  padding: "5px 10px",
  borderRadius: 8,
  cursor: "pointer",
  background: "transparent",
  color: "var(--dsw-alias-label-primary, CanvasText)",
  border: "1px solid var(--dsw-alias-border-secondary, rgba(127,127,127,0.35))",
  font: "inherit"
};
var primaryButton = {
  ...terseButton,
  background: "var(--dsw-alias-brand-primary, #4d6bfe)",
  color: "#fff",
  border: "1px solid transparent",
  fontWeight: 600
};
var inputStyle = {
  width: "100%",
  boxSizing: "border-box",
  padding: "8px 10px",
  borderRadius: 10,
  resize: "vertical",
  background: "var(--dsw-alias-bg-base, Canvas)",
  color: "var(--dsw-alias-label-primary, CanvasText)",
  border: "1px solid var(--dsw-alias-border-secondary, rgba(127,127,127,0.35))",
  font: "inherit"
};
var fileRowStyle = {
  display: "flex",
  alignItems: "center",
  gap: 8,
  padding: "2px 0",
  whiteSpace: "nowrap",
  overflow: "hidden"
};
var mutedStyle = {
  color: "var(--dsw-alias-label-secondary, GrayText)",
  fontSize: 12
};
function candidatesOf(sessionCwds, workspacePaths) {
  const seen = /* @__PURE__ */ new Set();
  const out = [];
  for (const path of [...sessionCwds, ...workspacePaths]) {
    if (path === void 0 || path === "") continue;
    const key = path.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(path);
  }
  return out;
}
function candidatesKey(candidates) {
  return candidates.map((path) => path.toLowerCase()).join("\0");
}
function nextTick() {
  return new Promise((resolve) => setTimeout(resolve, 0));
}
function Panel(props) {
  const { t, git, useGitCommitStatus, setStatus, useSessions, useWorkspaces } = props;
  const status = useGitCommitStatus((current) => current ?? null);
  const sessionCwds = useSessions(
    (state) => state.ids.map((id) => state.byId[id]?.cwd),
    sameArray
  );
  const workspacePaths = useWorkspaces(
    (snapshot) => snapshot.items.map((item) => item.path),
    sameArray
  );
  const candidates = (0, import_react.useMemo)(
    () => candidatesOf(sessionCwds, workspacePaths),
    [sessionCwds, workspacePaths]
  );
  const candidateKey = candidatesKey(candidates);
  const [open, setOpen] = (0, import_react.useState)(false);
  const [message, setMessage] = (0, import_react.useState)("");
  const [hint, setHint] = (0, import_react.useState)("");
  const [stageAll, setStageAll] = (0, import_react.useState)(true);
  const [showFiles, setShowFiles] = (0, import_react.useState)(false);
  const [busy, setBusy] = (0, import_react.useState)("idle");
  const [error, setError] = (0, import_react.useState)(null);
  const [notice, setNotice] = (0, import_react.useState)("");
  const candidatesRef = (0, import_react.useRef)(candidates);
  candidatesRef.current = candidates;
  const statusRef = (0, import_react.useRef)(status);
  statusRef.current = status;
  const inFlightRef = (0, import_react.useRef)(false);
  const lastScanRef = (0, import_react.useRef)(0);
  const mountedRef = (0, import_react.useRef)(true);
  (0, import_react.useEffect)(() => () => {
    mountedRef.current = false;
  }, []);
  const probe = (0, import_react.useCallback)(async (path) => {
    const result = await git.status(path);
    if (!result.ok) return null;
    const value = result.value;
    if (value === null || !value.hasUnstagedChanges) return null;
    return value;
  }, [git]);
  const refresh = (0, import_react.useCallback)(async (force) => {
    if (inFlightRef.current) return;
    const now = Date.now();
    if (!force && now - lastScanRef.current < SCAN_MIN_INTERVAL_MS) return;
    inFlightRef.current = true;
    try {
      const current = statusRef.current;
      if (current !== null) {
        const stillChanged = await probe(current.workspace);
        if (stillChanged !== null) {
          setStatus(stillChanged);
          return;
        }
      }
      for (const candidate of candidatesRef.current) {
        const found = await probe(candidate);
        if (!mountedRef.current) return;
        if (found !== null) {
          setStatus(found);
          return;
        }
        await nextTick();
      }
      setStatus(null);
    } finally {
      inFlightRef.current = false;
      lastScanRef.current = Date.now();
    }
  }, [probe, setStatus]);
  (0, import_react.useEffect)(() => {
    void refresh(true);
  }, [candidateKey, refresh]);
  (0, import_react.useEffect)(() => {
    const onFocus = () => {
      void refresh(false);
    };
    const onVisible = () => {
      if (document.visibilityState === "visible") void refresh(false);
    };
    window.addEventListener("focus", onFocus);
    document.addEventListener("visibilitychange", onVisible);
    const timer = window.setInterval(() => {
      if (document.visibilityState === "visible") void refresh(false);
    }, POLL_INTERVAL_MS);
    return () => {
      window.removeEventListener("focus", onFocus);
      document.removeEventListener("visibilitychange", onVisible);
      window.clearInterval(timer);
    };
  }, [refresh]);
  const unstagedFiles = (0, import_react.useMemo)(
    () => (status?.files ?? []).filter((file) => file.unstaged),
    [status]
  );
  const stagedCount = status?.summary.staged ?? 0;
  const onRefresh = (0, import_react.useCallback)(() => {
    setError(null);
    void refresh(true);
  }, [refresh]);
  const onGenerate = (0, import_react.useCallback)(async () => {
    if (status === null) return;
    setBusy("generating");
    setError(null);
    setNotice("");
    try {
      const result = await git.generate(status.workspace, {
        staged: !stageAll && stagedCount > 0,
        locale: typeof navigator === "undefined" ? "en" : navigator.language,
        ...hint.trim() === "" ? {} : { hint: hint.trim() }
      });
      if (!result.ok) {
        setError(result.error);
        return;
      }
      setMessage(result.value.message);
    } finally {
      setBusy("idle");
    }
  }, [git, hint, stageAll, stagedCount, status]);
  const onCommit = (0, import_react.useCallback)(async (push) => {
    if (status === null) return;
    if (message.trim() === "") {
      setError({ code: "bad-request", message: t("emptyMessage") });
      return;
    }
    setBusy("committing");
    setError(null);
    setNotice("");
    try {
      const result = await git.commit({
        path: status.workspace,
        message,
        stageAll,
        push
      });
      if (!result.ok) {
        setError(result.error);
        return;
      }
      setMessage("");
      setNotice(describeCommit(result.value, t));
      setStatus(null);
      await refresh(true);
    } finally {
      setBusy("idle");
    }
  }, [git, message, refresh, setStatus, stageAll, status, t]);
  if (status === null) return null;
  const branchLabel = status.detached || status.branch === null ? t("detached") : status.branch;
  if (!open) {
    return /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("button", { type: "button", style: badgeStyle, title: t("badgeTitle"), onClick: () => setOpen(true), children: [
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { "aria-hidden": "true", children: "\u2442" }),
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { children: branchLabel }),
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { style: mutedStyle, children: t("badgeFiles", { count: status.summary.unstaged }) })
    ] });
  }
  const committing = busy === "committing";
  const generating = busy === "generating";
  const canCommit = message.trim() !== "" && !committing && (stageAll ? status.files.length > 0 : stagedCount > 0);
  return /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("section", { style: panelStyle, role: "dialog", "aria-label": t("title"), children: [
    /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("header", { style: { display: "flex", alignItems: "baseline", gap: 8 }, children: [
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)("strong", { style: { flex: 1 }, children: t("title") }),
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { style: mutedStyle, children: branchLabel }),
      status.upstream !== null && (status.ahead > 0 || status.behind > 0) ? /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { style: mutedStyle, children: t("upstreamAheadBehind", { ahead: status.ahead, behind: status.behind }) }) : null,
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)("button", { type: "button", style: terseButton, onClick: onRefresh, title: t("refresh"), children: "\u21BB" }),
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
        "button",
        {
          type: "button",
          style: terseButton,
          onClick: () => {
            setOpen(false);
            setError(null);
            setNotice("");
          },
          title: t("close"),
          children: "\u2715"
        }
      )
    ] }),
    /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { style: mutedStyle, children: t("fileCount", {
      total: status.summary.total,
      staged: status.summary.staged,
      unstaged: status.summary.unstaged
    }) }),
    /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
      "button",
      {
        type: "button",
        style: { ...terseButton, textAlign: "left" },
        onClick: () => setShowFiles((value) => !value),
        children: showFiles ? t("hideFiles") : t("showFiles")
      }
    ),
    showFiles ? /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { style: { maxHeight: 160, overflow: "auto", fontFamily: "ui-monospace, monospace", fontSize: 12 }, children: [
      unstagedFiles.length === 0 ? /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { style: mutedStyle, children: t("noUnstaged") }) : null,
      unstagedFiles.map((file) => /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { style: fileRowStyle, title: file.path, children: [
        /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { style: { width: 12, flex: "none", opacity: 0.8 }, children: KIND_MARK[file.kind] }),
        /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { style: { overflow: "hidden", textOverflow: "ellipsis" }, children: file.from === void 0 ? file.path : `${file.from} \u2192 ${file.path}` })
      ] }, `${file.path}:${file.from ?? ""}`))
    ] }) : null,
    /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("label", { style: { display: "flex", flexDirection: "column", gap: 4 }, children: [
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { style: mutedStyle, children: t("messageLabel") }),
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
        "textarea",
        {
          rows: 3,
          style: inputStyle,
          value: message,
          placeholder: t("messagePlaceholder"),
          onChange: (event) => setMessage(event.target.value),
          onKeyDown: (event) => {
            if ((event.metaKey || event.ctrlKey) && event.key === "Enter" && canCommit) {
              event.preventDefault();
              void onCommit(false);
            }
          }
        }
      )
    ] }),
    /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("label", { style: { display: "flex", flexDirection: "column", gap: 4 }, children: [
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { style: mutedStyle, children: t("hintLabel") }),
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
        "input",
        {
          style: inputStyle,
          value: hint,
          placeholder: t("hintPlaceholder"),
          onChange: (event) => setHint(event.target.value)
        }
      )
    ] }),
    /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("label", { style: { display: "flex", alignItems: "center", gap: 8 }, children: [
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
        "input",
        {
          type: "checkbox",
          checked: stageAll,
          onChange: (event) => setStageAll(event.target.checked)
        }
      ),
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { children: t("stageAll") }),
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { style: mutedStyle, children: t("stageAllHint") })
    ] }),
    !stageAll && stagedCount === 0 ? /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { style: mutedStyle, children: t("noStaged") }) : null,
    error !== null ? /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { style: { color: "var(--dsw-alias-label-error, #d9534f)", whiteSpace: "pre-wrap" }, children: [
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { children: `${t("commitFailed")} [${error.code}] ${error.message}` }),
      error.detail !== void 0 && error.detail !== "" ? /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { style: { ...mutedStyle, maxHeight: 80, overflow: "auto" }, children: error.detail }) : null
    ] }) : null,
    notice !== "" ? /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { style: mutedStyle, children: notice }) : null,
    /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("footer", { style: { display: "flex", gap: 8, justifyContent: "flex-end", flexWrap: "wrap" }, children: [
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
        "button",
        {
          type: "button",
          style: terseButton,
          disabled: generating || committing,
          onClick: () => {
            void onGenerate();
          },
          children: generating ? t("generating") : t("generate")
        }
      ),
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
        "button",
        {
          type: "button",
          style: terseButton,
          disabled: !canCommit || committing,
          onClick: () => {
            void onCommit(false);
          },
          children: committing ? t("committing") : t("commit")
        }
      ),
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
        "button",
        {
          type: "button",
          style: primaryButton,
          disabled: !canCommit || committing,
          onClick: () => {
            void onCommit(true);
          },
          children: t("commitAndPush")
        }
      )
    ] })
  ] });
}
function sameArray(left, right) {
  if (left === right) return true;
  if (left.length !== right.length) return false;
  for (let index = 0; index < left.length; index += 1) {
    if (left[index] !== right[index]) return false;
  }
  return true;
}
function describeCommit(result, t) {
  const head = `${result.commit.slice(0, 8)} ${result.subject}`;
  if (!result.pushed) return head;
  return `${head} \xB7 ${t("commits")} ${t("andPush")}`;
}

// src/client/index.ts
var SLOT = "shell.overlay";
var STATUS_SOURCE = "gitCommitStatus";
var inject = ["slots", "locale", "sessions", "workspaces"];
function apply(ctx) {
  ctx.effect(() => ctx.locale.register(NS, { en, zh }), "dsh-git-commit-panel: dictionaries");
  const git = new GitCommitApi();
  let snapshot = null;
  const listeners = /* @__PURE__ */ new Set();
  const source = {
    getSnapshot: () => snapshot,
    subscribe: (listener) => {
      listeners.add(listener);
      return () => {
        listeners.delete(listener);
      };
    }
  };
  const publish = (next) => {
    if (next === snapshot) return;
    snapshot = next;
    for (const listener of [...listeners]) listener();
  };
  ctx.slots.inject(SLOT, () => ctx.slots.provideRoot({
    hooks: { [STATUS_SOURCE]: source }
  }));
  const Component = (props) => Panel({ ...props, git, setStatus: publish });
  ctx.slots.inject(SLOT, () => {
    const entry = {
      name: SLOT,
      id: "git-commit-panel",
      order: 50,
      locale: NS
    };
    const component = Component;
    return ctx.slots.register(entry, component);
  });
}
		return module.exports;
	}
});
