/**
 * Build script for dsh-git-commit-panel — the CLIENT half only.
 *
 * `lib/client.js` is a classic script (not an ES module): the DSH module
 * system executes it, it registers a factory on `window.__ModuleLoader__`, and
 * that factory materializes the bundle later. The client entry is therefore
 * bundled as CJS and wrapped in that factory closure, with the frozen browser
 * module table left external and everything else inlined (`require()` of
 * anything outside that table throws at runtime).
 *
 * The node half is emitted by `tsc` and must run AFTER this script, because
 * this script cleans `lib/`.
 *
 * @module dsh-git-commit-panel/scripts/build
 */
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, join, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

/** The plugin id; must equal the package name (it addresses `/plugins/<id>/client.js`). */
const PLUGIN_ID = 'dsh-git-commit-panel';

/**
 * Frozen browser module table (plus the specifiers the shared preset exempts).
 * A `require()` outside this list cannot resolve at runtime, so esbuild must
 * inline it instead of marking it external.
 */
const PLATFORM_MODULES = [
  'react',
  'react/jsx-runtime',
  'react-dom',
  'react-dom/client',
  '@deepseek-ai/cordis',
  '@deepseek-ai/dsh-client-store',
  '@deepseek-ai/dsh-client-ui-slots',
  '@deepseek-ai/dsh-client-ui-primitives',
  '@deepseek-ai/dsh-client-ui-dockkit',
];

const libDir = join(ROOT, 'lib');

console.log('[build] cleaning lib/');
await rm(libDir, { recursive: true, force: true });
await mkdir(libDir, { recursive: true });

console.log('[build] bundling lib/client.js');
const bundled = await build({
  entryPoints: [join(ROOT, 'src/client/index.ts')],
  bundle: true,
  write: false,
  format: 'cjs',
  platform: 'browser',
  target: 'es2022',
  jsx: 'automatic',
  jsxImportSource: 'react',
  legalComments: 'none',
  logLevel: 'warning',
  external: PLATFORM_MODULES,
  define: {
    'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV ?? 'production'),
  },
});

const [output] = bundled.outputFiles ?? [];
if (output === undefined) throw new Error('esbuild produced no client bundle');
// Drop esbuild's `// <entry>` banner comment; the wrapper below has its own.
const body = output.text.replace(/^\/\/[^\n]*\n/, '').trimEnd();
if (/^\s*(?:import|export)\s/m.test(body)) {
  throw new Error('client bundle still contains a module statement; platform imports must be external');
}

const clientPath = join(libDir, 'client.js');
await writeFile(
  clientPath,
  [
    '// Generated by scripts/build.mjs — do not edit; edit src/client instead.',
    `window.__ModuleLoader__.load({`,
    `\tid: ${JSON.stringify(PLUGIN_ID)},`,
    `\tfactory: (require) => {`,
    '\t\tvar module = { exports: {} };',
    '\t\tvar exports = module.exports;',
    '\t\tObject.defineProperty(exports, Symbol.toStringTag, { value: "Module" });',
    body,
    '\t\treturn module.exports;',
    '\t}',
    '});',
    '',
  ].join('\n'),
  'utf8',
);
console.log(`[build] wrote ${relative(ROOT, clientPath).split(sep).join('/')}`);
console.log('[build] done');
